# simple build for node.js application
# two parallel jobs
# write workflow context to output
# can be triggered manually
name: Build example

on:
  push:
    branches:
      - 'octocat/**'
  workflow_dispatch:

jobs:

  build:
    env:
      NODE_VERSION: 14.x
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Run npm
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    
  hello-windows:
    
    runs-on: windows-latest
    
    steps:
      - name: Say hello
        run: echo "Hello Windows runner!"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"