# matrix build with multiple runners and node versions
# includes and excludes for matrix strategy
name: Matrix example

on: 
  push:
    paths-ignore:
    - '.gitignore'
    - 'docs/**'
    - '.github/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run npm
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true

  hello-windows:
    
    runs-on: windows-latest
    
    steps:
      - name: Say hello
        run: echo "Hello Windows runner!"
        
  success:
    needs: build
    if: ${{ success() }}    

    runs-on: ubuntu-latest
    
    steps:
    - name: View context attributes
      uses: actions/github-script@v3
      with:
        script: console.log(context)

  fail:
    needs: build
    if: ${{ failure() }}

    runs-on: ubuntu-latest
    
    steps:
      - name: Create issue
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentBody = `
            👋 Hey, I ended up with a build failure.`
            await github.issues.create({
              ...context.repo,
              title: '⚠️ Build failure',
              labels: ['bug'],
              body: commentBody
            })