# publish package to package registry
name: Publish package

on: 
  workflow_dispatch:

jobs:
  publish-gpr:
    env:
      NODE_VERSION: 14.x

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: https://npm.pkg.github.com/
        scope: '@bas'
    - run: npm ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
